//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerParcial.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class acciones
    {
        [DisplayName("Código")]
        public int id { get; set; }

        [DisplayName("Fecha")]
        public string fecha { get; set; }

        [DisplayName("Precio de la accion")]
        public Nullable<double> precioAccion { get; set; }

        [DisplayName("Dinero invertido")]
        public Nullable<double> dineroInvertido { get; set; }

        [DisplayName("Acciones Operadas")]
        public Nullable<int> accionesOperadas { get; set; }
    }
}
